#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Configuration that should remain private
[[ -s "${HOME}/.secrets" ]] && source "${HOME}/.secrets"

# powerlevel
export TERM="xterm-256color"
POWERLEVEL9K_MODE='awesome-patched'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator)

POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_unique"

POWERLEVEL9K_STATUS_OK=false

# Add N in case it's present
export N_PREFIX=$HOME/.n
[ -d $N_PREFIX ] && export PATH=$N_PREFIX/bin:$PATH

# Edit with emacs
export EDITOR="emacsclient"
export ALTERNATE_EDITOR="emacs"

# Set up java
if [ -z "${JAVA_HOME}" ]; then
  export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
fi
